# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_file_type', models.CharField(max_length=250)),
                ('answer_file_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginID', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginID', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher'),
        ),
    ]
