# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_answer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer_table',
        ),
    ]
