# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_answer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_no', models.IntegerField()),
                ('Answer_value', models.CharField(max_length=1)),
            ],
        ),
    ]
